imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:      { fallback: de }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  de
    session:         ~

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_dbname%
        user:     %database_user%
        password: %database_pass%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

knp_menu:
    twig:
        template: "KcbBonnligaWebsiteBundle:Layout:menu.html.twig"
